interface CertificatesOption {
  title: string;
  business: string;
  imageURL: string;
  link: string;
  date: string;
}

export const certificateOptions: CertificatesOption[] = [
  {
    title: "Certificado Curso de Formação de Oficiais da Reserva",
    business: "Exército Brasileiro",
    imageURL: "./logo/eb-logo.svg",
    link: "https://drive.google.com/file/d/19ZOLZcLMNPVyTwvIv53n_EVrMwmnKBo9/view?usp=drivesdk",
    date: "December 2021",
  },
  {
    title: "CC50 - O Curso de Ciência da Computação de Harvard",
    business: "Foundation Estudar",
    imageURL: "./logo/fundacaoestudar-logo.jpeg",
    link: "https://drive.google.com/file/d/1MzE6Adul78J7GzschuXvtDCHonvXNh9R/view?usp=sharing",
    date: "November 2022",
  },
  {
    title: "FSW Barber - FullStack",
    business: "Full Stack Club",
    imageURL: "./logo/fullstackclub-logo.jpeg",
    link: "https://drive.google.com/file/d/1HLIascIoPvRkNY1MsxZK-Jzgxd7RpeVO/view?usp=sharing",
    date: "August 2024",
  },
  {
    title: "SQL Server: Formação Básica",
    business: "Linkedin Learning",
    imageURL: "./icons/linkedin-icon.svg",
    link: "https://www.linkedin.com/learning/certificates/32a0e15303d0e79b2eff0038d8faa9e46336ec6c942fbe3464546551ea3ec878?trk=share_certificate",
    date: "August 2024",
  },
  {
    title: "NLW Journey - Nodejs",
    business: "Rocketseat",
    imageURL: "./logo/rocketseat-logo.jpeg",
    link: "https://app.rocketseat.com.br/certificates/27b98f89-e622-43da-8179-5b0489f6498b",
    date: "July 2024",
  },
  {
    title: "NLW Journey - Reactjs",
    business: "Rocketseat",
    imageURL: "./logo/rocketseat-logo.jpeg",
    link: "https://app.rocketseat.com.br/certificates/640e5b13-f825-4f55-9739-6663ee2dfaa2",
    date: "July 2024",
  },
  {
    title: "NLW Unite - Nodejs",
    business: "Rocketseat",
    imageURL: "./logo/rocketseat-logo.jpeg",
    link: "https://app.rocketseat.com.br/certificates/b77e7d04-7f33-410a-89ec-ccd6feda8884",
    date: "April 2024",
  },
  {
    title: "NLW Unite - Reactjs",
    business: "Rocketseat",
    imageURL: "./logo/rocketseat-logo.jpeg",
    link: "https://app.rocketseat.com.br/certificates/a087a4e8-7618-441d-b8e5-acc383796bc3",
    date: "April 2024",
  },
  {
    title: "Imersão Front-End",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/immersion/certificate/8e3b232a-17f8-4792-bd52-f4e6bd57e751",
    date: "February 2024",
  },
  {
    title: "NLW Expert trilha de React",
    business: "Rocketseat",
    imageURL: "./logo/rocketseat-logo.jpeg",
    link: "https://app.rocketseat.com.br/certificates/15729af3-5971-4462-a4fa-118dbe01bfe6",
    date: "February 2024",
  },
  {
    title: "JavaScript: métodos de array",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/5c34564f-85d4-4147-85f9-6a9d5faef8d4",
    date: "January 2023",
  },
  {
    title: "JavaScript: consumindo e tratando dados de uma API",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/f5c43771-b500-4555-a7f2-c8db3b187395",
    date: "December 2022",
  },
  {
    title: "JavaScript na Web: armazenando dados no navegador",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/646de101-896c-4080-8d16-bb57807a3d4c",
    date: "November 2022",
  },
  {
    title: "JavaScript na Web: validação de Formulários e HTML5",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/ab506661-c49e-4af7-b71e-1f139cfbf19f",
    date: "November 2022",
  },
  {
    title: "JavaScript: manipulando o DOM",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/f44d3c2f-32b3-4be7-b7fa-5fc537a4b367",
    date: "November 2022",
  },
  {
    title: "JavaScript: validações e reconhecimento de voz",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/d5e2c6fc-7292-4784-a7f1-e2dfb8f24243",
    date: "November 2022",
  },
  {
    title: "Certificado Dev Festival Kenzie Academy",
    business: "Kenzie Academy Brazil",
    imageURL: "./logo/kenzie-logo.jpeg",
    link: "https://drive.google.com/file/d/1bkd8K7HRDLl9wlRs8ud_twSWfvJpZiqq/view?usp=drivesdk",
    date: "October 2022",
  },
  {
    title: "JavaScript para Web: Crie páginas dinâmicas",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/3e6c2965-144e-4776-ade7-2f2c3effb885",
    date: "September 2022",
  },
  {
    title: "JavaScript: explorando a linguagem",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/accbc3bf-c4c6-457d-87ea-62cdb64d1731",
    date: "June 2022",
  },
  {
    title: "Flexbox: posicione elementos na tela",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/a52fde48-908e-465c-9f87-f705807ec170",
    date: "May 2022",
  },
  {
    title: "HTML5 e CSS3 parte 1: a primeira página da Web",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/ec6767e9-ccf3-4474-88c9-406e1ac3aade",
    date: "April 2022",
  },
  {
    title: "HTML5 e CSS3 parte 2: posicionamento, listas e navegação",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/fae96841-b5d5-462a-a6d4-959870c0c1d5",
    date: "April 2022",
  },
  {
    title: "HTML5 e CSS3 parte 3: trabalhando com formulários e tabelas",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/9777c3d8-2aab-41cc-9358-1ab4015220d9",
    date: "April 2022",
  },
  {
    title: "HTML5 e CSS3 parte 4: avançando no CSS",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/f63d4d96-b848-48a2-81e8-e9651ac792d6",
    date: "April 2022",
  },
  {
    title: "C I: introdução à Linguagem das Linguagens",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/787292a9-3e61-4da6-8bb7-c78ca3b4494e",
    date: "March 2022",
  },
  {
    title: "C II: avançando na linguagem",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/042bbcbb-9ea9-4797-94f0-328968091982",
    date: "March 2022",
  },
  {
    title: "C III: recursos avançados da linguagem",
    business: "Alura",
    imageURL: "./logo/alura-logo.jpeg",
    link: "https://cursos.alura.com.br/certificate/9fabaf43-21dc-4cd4-a8b3-96155e08ae0e",
    date: "April 2022",
  },
  {
    title: "Certificado Maratona de Programação Kenzie Academy",
    business: "Kenzie Academy Brazil",
    imageURL: "./logo/kenzie-logo.jpeg",
    link: "https://drive.google.com/file/d/1zQwpFupgZ2w47t4hmilmu3iywpjjznQH/view?usp=sharing",
    date: "February 2022",
  },
  {
    title:
      "Certificado Curso de Extensão HTML - parte 1: Introdução ao desenvolvimento de páginas web",
    business: "IFRS",
    imageURL: "./logo/ifrs-logo.jpeg",
    link: "https://drive.google.com/file/d/1Z0EuRXu2HuiZecMYTEDzk-JhcGM3t_37/view?usp=sharing",
    date: "April 2020",
  },
  {
    title: "Certificado Curso de Extensão HTML: tabelas e formulários",
    business: "IFRS",
    imageURL: "./logo/ifrs-logo.jpeg",
    link: "https://drive.google.com/file/d/1dY_alvb3JhaB4JsTi-p47TH5CfdfpXF_/view?usp=sharing",
    date: "April 2020",
  },
];
